version: '{build}'
clone_depth: 3
init:
  - cmd: >-
    set PATH=%PATH:C:\Program Files\Git\usr\bin;=%;C:\MinGW\bin;

build_script:
  - cmd: >-
    mkdir build

    cd build

    cmake -G "MinGW Makefiles" ..

    cmake --build . --target mbc_test
test: off
deploy: off
