os: linux
dist: trusty
language: c
git:
  depth: 3
compiler:
  - clang
  - gcc
script:
  - mkdir build && cd build
  - cmake ..
  - make mbc_test
notifications:
  email: false
  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify
    on_success: change
    on_failure: always
    on_cancel: never
    on_error: always
