language: c
dist: trusty
compiler:
  - clang
  - gcc
install: true
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - cd ../test
  - bash test.sh 128K 8K
notifications:
  email: false
  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify
    on_success: change
    on_failure: always
    on_cancel: never
    on_error: always
